CC = g++
CFLAGS = -std=c++11

all: containsDuplicate validAnagram twoSum

containsDuplicate: containsDuplicate.cpp
	$(CC) $(CFLAGS) -o containsDuplicate containsDuplicate.cpp

validAnagram: validAnagram.cpp
	$(CC) $(CFLAGS) -o validAnagram validAnagram.cpp
twoSum: twoSum.cpp
	$(CC) $(CFLAGS) -o twoSum twoSum.cpp
clean:
	rm -f containsDuplicate validAnagram twoSum
