CC = g++
CFLAGS = -std=c++11

all: containsDuplicate validAnagram

containsDuplicate: containsDuplicate.cpp
	$(CC) $(CFLAGS) -o containsDuplicate containsDuplicate.cpp

validAnagram: validAnagram.cpp
	$(CC) $(CFLAGS) -o validAnagram validAnagram.cpp
clean:
	rm -f containsDuplicate validAnagram
