name: Golang Workflow

on:
  push:
    branches:
      - "main"
      - "golang"

  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Directory Structure
        run: |
          pwd
          ls -R
          
      - name: Change permission of script
        run: |
          chmod +x .github/workflows/golang.sh

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Run Go Tests
        run: |
          ./.github/workflows/golang.sh
